version: "3.6"
services:
  #Backend Api
  smart-brain-api:
    container_name: backend
    #image: node:13.14.0
    build: ./
    command: npm start
    working_dir: /user/src/smart-brain-api
    ports:
      - "3001:3001"
    environment:
      POSTGRES_URI: postgres://postgres:yomibaloo1@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    volumes:
      - ./:/user/src/smart-brain-api

  # Postgres Database
  postgres:
    environment:
      POSTGRES_PASSWORD: yomibaloo1
      POSTGRES_USER: postgres
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    restart: always
    build: ./postgres
    ports:
      - "5433:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
